-- Datos operativos de arranque: salon y carta del Restaurante El Patio.
--
-- Generado desde src/compartido/datosSemilla.ts, que fue la fuente de verdad
-- del prototipo. Los usuarios NO se siembran aqui: los crea SembradorUsuarios
-- al arrancar por primera vez, con claves aleatorias que se imprimen una sola
-- vez en consola. Una clave escrita en una migracion es una clave publicada.

-- Salon
INSERT INTO mesas (id, numero, nombre, zona, capacidad, estado) VALUES ('m1', 1, NULL, 'salon', 2, 'libre');
INSERT INTO mesas (id, numero, nombre, zona, capacidad, estado) VALUES ('m2', 2, NULL, 'salon', 2, 'libre');
INSERT INTO mesas (id, numero, nombre, zona, capacidad, estado) VALUES ('m3', 3, NULL, 'salon', 4, 'libre');
INSERT INTO mesas (id, numero, nombre, zona, capacidad, estado) VALUES ('m4', 4, NULL, 'salon', 4, 'libre');
INSERT INTO mesas (id, numero, nombre, zona, capacidad, estado) VALUES ('m5', 5, NULL, 'salon', 4, 'libre');
INSERT INTO mesas (id, numero, nombre, zona, capacidad, estado) VALUES ('m6', 6, NULL, 'salon', 6, 'libre');
INSERT INTO mesas (id, numero, nombre, zona, capacidad, estado) VALUES ('m7', 7, NULL, 'salon', 6, 'libre');
INSERT INTO mesas (id, numero, nombre, zona, capacidad, estado) VALUES ('m8', 8, NULL, 'salon', 4, 'libre');
INSERT INTO mesas (id, numero, nombre, zona, capacidad, estado) VALUES ('m9', 9, NULL, 'salon', 2, 'libre');
INSERT INTO mesas (id, numero, nombre, zona, capacidad, estado) VALUES ('m10', 10, NULL, 'salon', 8, 'libre');
INSERT INTO mesas (id, numero, nombre, zona, capacidad, estado) VALUES ('m11', 11, 'Terraza 1', 'terraza', 4, 'libre');
INSERT INTO mesas (id, numero, nombre, zona, capacidad, estado) VALUES ('m12', 12, 'Terraza 2', 'terraza', 4, 'libre');
INSERT INTO mesas (id, numero, nombre, zona, capacidad, estado) VALUES ('m13', 13, 'Terraza 3', 'terraza', 6, 'libre');
INSERT INTO mesas (id, numero, nombre, zona, capacidad, estado) VALUES ('m14', 14, 'Terraza 4', 'terraza', 6, 'libre');
INSERT INTO mesas (id, numero, nombre, zona, capacidad, estado) VALUES ('m15', 15, 'Terraza 5', 'terraza', 2, 'libre');
INSERT INTO mesas (id, numero, nombre, zona, capacidad, estado) VALUES ('m16', 16, 'Privado 1', 'privado', 8, 'libre');
INSERT INTO mesas (id, numero, nombre, zona, capacidad, estado) VALUES ('m17', 17, 'Privado 2', 'privado', 10, 'libre');
INSERT INTO mesas (id, numero, nombre, zona, capacidad, estado) VALUES ('m18', 18, 'Privado 3', 'privado', 12, 'libre');

-- Categorias de la carta
INSERT INTO categorias_carta (id, nombre, orden) VALUES ('c1', 'Entradas y picadas', 1);
INSERT INTO categorias_carta (id, nombre, orden) VALUES ('c2', 'Fusión de autor', 2);
INSERT INTO categorias_carta (id, nombre, orden) VALUES ('c3', 'Carnes y parrilla', 3);
INSERT INTO categorias_carta (id, nombre, orden) VALUES ('c4', 'Pescados y mariscos', 4);
INSERT INTO categorias_carta (id, nombre, orden) VALUES ('c5', 'Pastas y risottos', 5);
INSERT INTO categorias_carta (id, nombre, orden) VALUES ('c6', 'Guarniciones', 6);
INSERT INTO categorias_carta (id, nombre, orden) VALUES ('c7', 'Postres', 7);
INSERT INTO categorias_carta (id, nombre, orden) VALUES ('c8', 'Coctelería de autor', 8);
INSERT INTO categorias_carta (id, nombre, orden) VALUES ('c9', 'Coctelería clásica', 9);
INSERT INTO categorias_carta (id, nombre, orden) VALUES ('c10', 'Cervezas y bebidas', 10);

-- Productos
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p01', 'c1', 'Croquetas de arroz de coco', 'Rellenas de posta negra cartagenera, queso criollo y suero costeño.', 22000, TRUE, 12, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p02', 'c1', 'Ceviche El Patio', 'Pescado del día en leche de tigre de maracuyá, camarón y chips de plátano.', 32000, TRUE, 10, 'cocina', '[{"id":"mod_picante","nombre":"Punto de picante","tipo":"seleccion_unica","obligatorio":false,"opciones":[{"nombre":"Sin picante","precioAdicional":0},{"nombre":"Suave","precioAdicional":0},{"nombre":"Fuerte","precioAdicional":0}]}]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p03', 'c1', 'Carpaccio de pulpo', 'Láminas finas de pulpo, aceite de oliva, alcaparras y limón amarillo.', 34000, TRUE, 10, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p04', 'c1', 'Tartar de atún y aguacate', 'Atún fresco marinado en soya y ajonjolí sobre cama de aguacate.', 35000, TRUE, 12, 'cocina', '[{"id":"mod_sin","nombre":"Preparar sin","tipo":"seleccion_multiple","obligatorio":false,"opciones":[{"nombre":"Sin cebolla","precioAdicional":0},{"nombre":"Sin cilantro","precioAdicional":0},{"nombre":"Sin picante","precioAdicional":0},{"nombre":"Sin queso","precioAdicional":0}]}]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p05', 'c1', 'Chicharrón crocante', 'Panceta de cerdo crocante con guacamole, patacón y suero costeño.', 26000, TRUE, 15, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p06', 'c1', 'Alitas glaseadas en tamarindo', 'Ocho alitas con glaseado de tamarindo y ajonjolí tostado.', 28000, TRUE, 18, 'cocina', '[{"id":"mod_picante","nombre":"Punto de picante","tipo":"seleccion_unica","obligatorio":false,"opciones":[{"nombre":"Sin picante","precioAdicional":0},{"nombre":"Suave","precioAdicional":0},{"nombre":"Fuerte","precioAdicional":0}]}]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p07', 'c1', 'Burrata criolla', 'Burrata fresca con tomates asados, albahaca y reducción de panela.', 30000, TRUE, 8, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p08', 'c1', 'Empanaditas de langostino', 'Seis unidades con alioli de ají amarillo.', 24000, TRUE, 14, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p09', 'c2', 'Róbalo al bijao', 'Cocción lenta en hoja de bijao sobre arroz cremoso de ají amarillo, leche de coco y achiote.', 58000, TRUE, 25, 'cocina', '[{"id":"mod_sin","nombre":"Preparar sin","tipo":"seleccion_multiple","obligatorio":false,"opciones":[{"nombre":"Sin cebolla","precioAdicional":0},{"nombre":"Sin cilantro","precioAdicional":0},{"nombre":"Sin picante","precioAdicional":0},{"nombre":"Sin queso","precioAdicional":0}]}]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p10', 'c2', 'Lomo encostrado en quinua', 'Medallón de lomo fino sobre arroz cremoso de cilantro y frutos del mar.', 64000, TRUE, 24, 'cocina', '[{"id":"mod_termino","nombre":"Término de la carne","tipo":"seleccion_unica","obligatorio":true,"opciones":[{"nombre":"Sellado","precioAdicional":0},{"nombre":"Término medio","precioAdicional":0},{"nombre":"Tres cuartos","precioAdicional":0},{"nombre":"Bien asado","precioAdicional":0}]}]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p11', 'c2', 'Cerdo laqueado en panela', 'Lomo de cerdo laqueado en panela y soya con puré de ñame y encurtido de cebolla.', 52000, TRUE, 22, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p12', 'c2', 'Arroz cremoso de jaiba y coco', 'Carne de jaiba, leche de coco y bisque, terminado con maíz tierno.', 56000, TRUE, 22, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p13', 'c2', 'Tataki de res al ajonjolí', 'Lomo sellado en costra de ajonjolí con vinagreta de maracuyá y ají.', 60000, FALSE, 20, 'cocina', '[{"id":"mod_termino","nombre":"Término de la carne","tipo":"seleccion_unica","obligatorio":true,"opciones":[{"nombre":"Sellado","precioAdicional":0},{"nombre":"Término medio","precioAdicional":0},{"nombre":"Tres cuartos","precioAdicional":0},{"nombre":"Bien asado","precioAdicional":0}]}]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p14', 'c3', 'Tomahawk 800 g', 'Corte con hueso marinado en sal gruesa y vino tinto. Ideal para compartir.', 118000, TRUE, 35, 'cocina', '[{"id":"mod_termino","nombre":"Término de la carne","tipo":"seleccion_unica","obligatorio":true,"opciones":[{"nombre":"Sellado","precioAdicional":0},{"nombre":"Término medio","precioAdicional":0},{"nombre":"Tres cuartos","precioAdicional":0},{"nombre":"Bien asado","precioAdicional":0}]},{"id":"mod_guarnicion","nombre":"Guarnición","tipo":"seleccion_unica","obligatorio":true,"opciones":[{"nombre":"Papa criolla al romero","precioAdicional":0},{"nombre":"Puré de ñame","precioAdicional":0},{"nombre":"Yuca al vapor","precioAdicional":0},{"nombre":"Ensalada fresca","precioAdicional":0},{"nombre":"Vegetales baby","precioAdicional":3000},{"nombre":"Risotto de champiñones","precioAdicional":9000}]}]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p15', 'c3', 'Ojo de bife madurado 400 g', 'Corte madurado 30 días, sal parrilla y mantequilla de hierbas.', 92000, TRUE, 28, 'cocina', '[{"id":"mod_termino","nombre":"Término de la carne","tipo":"seleccion_unica","obligatorio":true,"opciones":[{"nombre":"Sellado","precioAdicional":0},{"nombre":"Término medio","precioAdicional":0},{"nombre":"Tres cuartos","precioAdicional":0},{"nombre":"Bien asado","precioAdicional":0}]},{"id":"mod_guarnicion","nombre":"Guarnición","tipo":"seleccion_unica","obligatorio":true,"opciones":[{"nombre":"Papa criolla al romero","precioAdicional":0},{"nombre":"Puré de ñame","precioAdicional":0},{"nombre":"Yuca al vapor","precioAdicional":0},{"nombre":"Ensalada fresca","precioAdicional":0},{"nombre":"Vegetales baby","precioAdicional":3000},{"nombre":"Risotto de champiñones","precioAdicional":9000}]}]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p16', 'c3', 'Punta de anca 350 g', 'A la parrilla con chimichurri de la casa.', 68000, TRUE, 25, 'cocina', '[{"id":"mod_termino","nombre":"Término de la carne","tipo":"seleccion_unica","obligatorio":true,"opciones":[{"nombre":"Sellado","precioAdicional":0},{"nombre":"Término medio","precioAdicional":0},{"nombre":"Tres cuartos","precioAdicional":0},{"nombre":"Bien asado","precioAdicional":0}]},{"id":"mod_guarnicion","nombre":"Guarnición","tipo":"seleccion_unica","obligatorio":true,"opciones":[{"nombre":"Papa criolla al romero","precioAdicional":0},{"nombre":"Puré de ñame","precioAdicional":0},{"nombre":"Yuca al vapor","precioAdicional":0},{"nombre":"Ensalada fresca","precioAdicional":0},{"nombre":"Vegetales baby","precioAdicional":3000},{"nombre":"Risotto de champiñones","precioAdicional":9000}]}]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p17', 'c3', 'Lomo fino en salsa de pimienta', 'Medallones de lomo bañados en salsa de pimienta y brandy.', 62000, TRUE, 22, 'cocina', '[{"id":"mod_termino","nombre":"Término de la carne","tipo":"seleccion_unica","obligatorio":true,"opciones":[{"nombre":"Sellado","precioAdicional":0},{"nombre":"Término medio","precioAdicional":0},{"nombre":"Tres cuartos","precioAdicional":0},{"nombre":"Bien asado","precioAdicional":0}]},{"id":"mod_guarnicion","nombre":"Guarnición","tipo":"seleccion_unica","obligatorio":true,"opciones":[{"nombre":"Papa criolla al romero","precioAdicional":0},{"nombre":"Puré de ñame","precioAdicional":0},{"nombre":"Yuca al vapor","precioAdicional":0},{"nombre":"Ensalada fresca","precioAdicional":0},{"nombre":"Vegetales baby","precioAdicional":3000},{"nombre":"Risotto de champiñones","precioAdicional":9000}]}]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p18', 'c3', 'Mar y tierra del Patio', 'Medallones de lomo al ajillo con langostinos salteados al brandy.', 72000, TRUE, 26, 'cocina', '[{"id":"mod_termino","nombre":"Término de la carne","tipo":"seleccion_unica","obligatorio":true,"opciones":[{"nombre":"Sellado","precioAdicional":0},{"nombre":"Término medio","precioAdicional":0},{"nombre":"Tres cuartos","precioAdicional":0},{"nombre":"Bien asado","precioAdicional":0}]},{"id":"mod_guarnicion","nombre":"Guarnición","tipo":"seleccion_unica","obligatorio":true,"opciones":[{"nombre":"Papa criolla al romero","precioAdicional":0},{"nombre":"Puré de ñame","precioAdicional":0},{"nombre":"Yuca al vapor","precioAdicional":0},{"nombre":"Ensalada fresca","precioAdicional":0},{"nombre":"Vegetales baby","precioAdicional":3000},{"nombre":"Risotto de champiñones","precioAdicional":9000}]}]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p19', 'c3', 'Churrasco de cerdo', 'Lomo de cerdo en mariposa a la parrilla con chimichurri.', 46000, TRUE, 20, 'cocina', '[{"id":"mod_guarnicion","nombre":"Guarnición","tipo":"seleccion_unica","obligatorio":true,"opciones":[{"nombre":"Papa criolla al romero","precioAdicional":0},{"nombre":"Puré de ñame","precioAdicional":0},{"nombre":"Yuca al vapor","precioAdicional":0},{"nombre":"Ensalada fresca","precioAdicional":0},{"nombre":"Vegetales baby","precioAdicional":3000},{"nombre":"Risotto de champiñones","precioAdicional":9000}]}]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p20', 'c3', 'Costillas BBQ de corozo', 'Cocción lenta de ocho horas con salsa artesanal de corozo.', 54000, TRUE, 18, 'cocina', '[{"id":"mod_guarnicion","nombre":"Guarnición","tipo":"seleccion_unica","obligatorio":true,"opciones":[{"nombre":"Papa criolla al romero","precioAdicional":0},{"nombre":"Puré de ñame","precioAdicional":0},{"nombre":"Yuca al vapor","precioAdicional":0},{"nombre":"Ensalada fresca","precioAdicional":0},{"nombre":"Vegetales baby","precioAdicional":3000},{"nombre":"Risotto de champiñones","precioAdicional":9000}]}]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p21', 'c3', 'Suprema de pollo rellena', 'Pechuga rellena de jamón, queso y cebolla caramelizada en salsa de champiñones.', 42000, TRUE, 22, 'cocina', '[{"id":"mod_guarnicion","nombre":"Guarnición","tipo":"seleccion_unica","obligatorio":true,"opciones":[{"nombre":"Papa criolla al romero","precioAdicional":0},{"nombre":"Puré de ñame","precioAdicional":0},{"nombre":"Yuca al vapor","precioAdicional":0},{"nombre":"Ensalada fresca","precioAdicional":0},{"nombre":"Vegetales baby","precioAdicional":3000},{"nombre":"Risotto de champiñones","precioAdicional":9000}]}]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p22', 'c4', 'Salmón en costra de ajonjolí', 'Filete de salmón con reducción de lulo y puré de ñame.', 68000, TRUE, 22, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p23', 'c4', 'Róbalo a la marinera', 'Filete marinado en cítricos bañado en salsa de frutos del mar.', 62000, TRUE, 24, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p24', 'c4', 'Mojarra con arroz titoté', 'Mojarra entera, arroz de coco titoté, patacones y aguacate.', 52000, TRUE, 25, 'cocina', '[{"id":"mod_preparacion","nombre":"Preparación","tipo":"seleccion_unica","obligatorio":true,"opciones":[{"nombre":"Frito","precioAdicional":0},{"nombre":"A la plancha","precioAdicional":0},{"nombre":"Al vapor","precioAdicional":0}]}]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p25', 'c4', 'Cazuela de mariscos gratinada', 'Frutos del mar en bisque atomatado, gratinados con mozzarella y parmesano.', 65000, TRUE, 26, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p26', 'c4', 'Langostinos al ajillo', 'Salteados en mantequilla, vino blanco y perejil, con arroz de coco.', 66000, TRUE, 20, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p27', 'c4', 'Pulpo a la parrilla', 'Tentáculo a la brasa sobre puré de ñame con aceite de pimentón.', 74000, TRUE, 28, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p28', 'c5', 'Ravioli de ricotta y albahaca', 'Pasta fresca en salsa pomodoro con parmesano curado.', 40000, TRUE, 18, 'cocina', '[{"id":"mod_sin","nombre":"Preparar sin","tipo":"seleccion_multiple","obligatorio":false,"opciones":[{"nombre":"Sin cebolla","precioAdicional":0},{"nombre":"Sin cilantro","precioAdicional":0},{"nombre":"Sin picante","precioAdicional":0},{"nombre":"Sin queso","precioAdicional":0}]}]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p29', 'c5', 'Fettuccine frutos del mar', 'Pasta salteada con mariscos, brandy y bisque atomatado.', 48000, TRUE, 20, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p30', 'c5', 'Risotto de champiñones', 'Arroz arbóreo, champiñones portobello y aceite de trufa.', 46000, TRUE, 24, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p31', 'c5', 'Boloñesa de la casa', 'Ragú de res cocido a fuego lento con tostadas gratinadas.', 38000, TRUE, 18, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p32', 'c5', 'Lasaña de berenjena', 'Capas de berenjena asada, pomodoro y queso gratinado. Opción vegetariana.', 38000, TRUE, 20, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p33', 'c6', 'Papa criolla al romero', 'Salteada con mantequilla de hierbas.', 12000, TRUE, 10, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p34', 'c6', 'Puré de ñame con albahaca', 'Cremoso, con queso costeño.', 12000, TRUE, 8, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p35', 'c6', 'Ensalada fresca de la casa', 'Mezcla verde, tomate cherry y vinagreta de maracuyá.', 14000, TRUE, 6, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p36', 'c6', 'Yuca al vapor con suero', 'Yuca criolla con suero costeño.', 10000, TRUE, 8, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p37', 'c6', 'Vegetales baby salteados', 'Zanahoria, arveja y calabacín al wok.', 14000, TRUE, 8, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p38', 'c7', 'Enyucado con helado', 'Postre tradicional de yuca y coco con helado de vainilla.', 18000, TRUE, 8, 'cocina', '[{"id":"mod_dedicatoria","nombre":"Dedicatoria en el plato","tipo":"texto_libre","obligatorio":false}]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p39', 'c7', 'Volcán de chocolate', 'Bizcocho tibio de centro líquido con helado de vainilla.', 20000, TRUE, 12, 'cocina', '[{"id":"mod_dedicatoria","nombre":"Dedicatoria en el plato","tipo":"texto_libre","obligatorio":false}]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p40', 'c7', 'Flan de coco y arequipe', 'Con salsa de caramelo y cereza.', 18000, TRUE, 6, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p41', 'c7', 'Cheesecake de corozo', 'Base de galleta con coulis de corozo del Caribe.', 22000, TRUE, 6, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p42', 'c7', 'Tiramisú del Patio', 'Con café de la sierra y cacao amargo.', 20000, TRUE, 6, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p43', 'c8', 'Carajillo del Patio', 'Espresso, licor de hierbas y espuma de panela.', 28000, TRUE, 5, 'bar', '[{"id":"mod_bar","nombre":"Preparación del bar","tipo":"seleccion_multiple","obligatorio":false,"opciones":[{"nombre":"Sin hielo","precioAdicional":0},{"nombre":"Menos dulce","precioAdicional":0},{"nombre":"Doble licor","precioAdicional":9000}]}]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p44', 'c8', 'Patio Sour', 'Corozo, cítricos y clara de huevo sobre base de ron añejo.', 30000, TRUE, 6, 'bar', '[{"id":"mod_bar","nombre":"Preparación del bar","tipo":"seleccion_multiple","obligatorio":false,"opciones":[{"nombre":"Sin hielo","precioAdicional":0},{"nombre":"Menos dulce","precioAdicional":0},{"nombre":"Doble licor","precioAdicional":9000}]}]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p45', 'c8', 'Mojito de tamarindo', 'Hierbabuena fresca, tamarindo y ron blanco.', 26000, TRUE, 5, 'bar', '[{"id":"mod_bar","nombre":"Preparación del bar","tipo":"seleccion_multiple","obligatorio":false,"opciones":[{"nombre":"Sin hielo","precioAdicional":0},{"nombre":"Menos dulce","precioAdicional":0},{"nombre":"Doble licor","precioAdicional":9000}]}]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p46', 'c8', 'Gin tónico botánico', 'Ginebra premium, tónica artesanal y botánicos de la casa.', 32000, TRUE, 4, 'bar', '[{"id":"mod_bar","nombre":"Preparación del bar","tipo":"seleccion_multiple","obligatorio":false,"opciones":[{"nombre":"Sin hielo","precioAdicional":0},{"nombre":"Menos dulce","precioAdicional":0},{"nombre":"Doble licor","precioAdicional":9000}]}]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p47', 'c8', 'Margarita de maracuyá', 'Tequila, maracuyá fresco y borde de sal ahumada.', 28000, TRUE, 5, 'bar', '[{"id":"mod_bar","nombre":"Preparación del bar","tipo":"seleccion_multiple","obligatorio":false,"opciones":[{"nombre":"Sin hielo","precioAdicional":0},{"nombre":"Menos dulce","precioAdicional":0},{"nombre":"Doble licor","precioAdicional":9000}]}]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p48', 'c8', 'Old Fashioned de panela', 'Whisky, panela ahumada y amargo de angostura.', 32000, TRUE, 5, 'bar', '[{"id":"mod_bar","nombre":"Preparación del bar","tipo":"seleccion_multiple","obligatorio":false,"opciones":[{"nombre":"Sin hielo","precioAdicional":0},{"nombre":"Menos dulce","precioAdicional":0},{"nombre":"Doble licor","precioAdicional":9000}]}]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p49', 'c9', 'Mojito clásico', 'Ron blanco, hierbabuena, limón y soda.', 24000, TRUE, 4, 'bar', '[{"id":"mod_bar","nombre":"Preparación del bar","tipo":"seleccion_multiple","obligatorio":false,"opciones":[{"nombre":"Sin hielo","precioAdicional":0},{"nombre":"Menos dulce","precioAdicional":0},{"nombre":"Doble licor","precioAdicional":9000}]}]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p50', 'c9', 'Piña colada', 'Crema de coco, piña y ron.', 26000, TRUE, 4, 'bar', '[{"id":"mod_bar","nombre":"Preparación del bar","tipo":"seleccion_multiple","obligatorio":false,"opciones":[{"nombre":"Sin hielo","precioAdicional":0},{"nombre":"Menos dulce","precioAdicional":0},{"nombre":"Doble licor","precioAdicional":9000}]}]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p51', 'c9', 'Daiquiri de fresa', 'Fresa natural, limón y ron blanco.', 24000, TRUE, 4, 'bar', '[{"id":"mod_bar","nombre":"Preparación del bar","tipo":"seleccion_multiple","obligatorio":false,"opciones":[{"nombre":"Sin hielo","precioAdicional":0},{"nombre":"Menos dulce","precioAdicional":0},{"nombre":"Doble licor","precioAdicional":9000}]}]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p52', 'c9', 'Coctel de la casa', 'El bartender lo prepara con el licor que elijas.', 22000, TRUE, 5, 'bar', '[{"id":"mod_licor","nombre":"Licor base","tipo":"seleccion_unica","obligatorio":true,"opciones":[{"nombre":"Ron","precioAdicional":0},{"nombre":"Vodka","precioAdicional":0},{"nombre":"Ginebra","precioAdicional":4000},{"nombre":"Tequila","precioAdicional":4000}]},{"id":"mod_bar","nombre":"Preparación del bar","tipo":"seleccion_multiple","obligatorio":false,"opciones":[{"nombre":"Sin hielo","precioAdicional":0},{"nombre":"Menos dulce","precioAdicional":0},{"nombre":"Doble licor","precioAdicional":9000}]}]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p53', 'c10', 'Cerveza nacional', 'Botella 330 ml bien fría.', 9000, TRUE, 1, 'bar', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p54', 'c10', 'Cerveza artesanal', 'Selección rotativa de cervecería local.', 16000, TRUE, 1, 'bar', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p55', 'c10', 'Limonada de coco', 'Jarra individual, cremosa y fría.', 14000, TRUE, 4, 'bar', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p56', 'c10', 'Limonada natural', 'En agua o en soda.', 8000, TRUE, 3, 'bar', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p57', 'c10', 'Jugo natural', 'Mango, maracuyá, lulo o corozo.', 9000, TRUE, 3, 'bar', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p58', 'c10', 'Agua sin gas', 'Botella 500 ml.', 6000, TRUE, 1, 'bar', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('p59', 'c10', 'Gaseosa', 'Botella personal.', 7000, TRUE, 1, 'bar', '[]'::jsonb);

