-- Carta 2026.
--
-- Reemplaza la carta de comida de la semilla V2 por la del menu impreso
-- «El Patio Menu 2026.pdf»: 10 categorias y 55 platos, con sus precios y
-- descripciones tal como estan en el papel.
--
-- LAS BEBIDAS NO SE TOCAN. Las tres categorias de barra —cocteleria de
-- autor, cocteleria clasica y cervezas— siguen igual y con sus mismos
-- identificadores. Solo se corren de puesto para quedar detras de la
-- comida nueva.
--
-- Borrar los platos viejos NO afecta las ventas ya cobradas:
-- `items_orden.item_carta_id` no es llave foranea y cada linea de comanda
-- guarda su propia copia del nombre y del precio (ver V1, tabla
-- items_orden). Una comanda de anoche sigue diciendo lo que se vendio y a
-- cuanto, aunque el plato ya no exista en la carta.

-- 1. Fuera la carta de comida anterior. Primero los platos: la categoria
--    no se puede borrar mientras algo apunte a ella (ON DELETE RESTRICT).
DELETE FROM items_carta WHERE categoria_id IN ('c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7');
DELETE FROM categorias_carta WHERE id IN ('c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7');

-- 2. Las bebidas pasan al final de la carta.
UPDATE categorias_carta SET orden = 11 WHERE id = 'c8';  -- Coctelería de autor
UPDATE categorias_carta SET orden = 12 WHERE id = 'c9';  -- Coctelería clásica
UPDATE categorias_carta SET orden = 13 WHERE id = 'c10';  -- Cervezas y bebidas

-- 3. Las categorias del menu 2026.
INSERT INTO categorias_carta (id, nombre, orden) VALUES ('entradas', 'Entradas', 1);
INSERT INTO categorias_carta (id, nombre, orden) VALUES ('carnes', 'Carnes', 2);
INSERT INTO categorias_carta (id, nombre, orden) VALUES ('pescados-y-mariscos', 'Pescados y mariscos', 3);
INSERT INTO categorias_carta (id, nombre, orden) VALUES ('pastas-artesanales', 'Pastas artesanales', 4);
INSERT INTO categorias_carta (id, nombre, orden) VALUES ('aves', 'Aves', 5);
INSERT INTO categorias_carta (id, nombre, orden) VALUES ('arroces', 'Arroces', 6);
INSERT INTO categorias_carta (id, nombre, orden) VALUES ('picada', 'Picada', 7);
INSERT INTO categorias_carta (id, nombre, orden) VALUES ('express', 'Express', 8);
INSERT INTO categorias_carta (id, nombre, orden) VALUES ('infantil', 'Infantil', 9);
INSERT INTO categorias_carta (id, nombre, orden) VALUES ('postre', 'Postre', 10);

-- 4. Los platos.
--
--    `tiempo_preparacion_min` es un estimado por categoria: el menu no
--    trae tiempos y la cocina es la unica que sabe cuanto tarda cada
--    plato. Corregirlos es un UPDATE, no una migracion nueva.
--
--    Los cinco cortes que se venden «con acompanante a su eleccion» lo
--    llevan como modificador obligatorio, sin recargo: el mesero tiene
--    que preguntarlo antes de mandar la comanda, no despues.

-- Entradas
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('entradas-trilogia-de-tacos', 'entradas', 'Trilogía de tacos', '- Tortilla de maíz frita rellena de camarones en salsa de mayonesa asiática y limón criollo. - Tortilla de maíz frita rellena de dados de chicharrón al barril en salsa verde mexicana. - Tortilla de maíz frita rellena de morrillo en cocción lenta desmechado y salteado con vegetales, salsa de la casa, salsa de ajo, salsa soya y cilantro. *Acompañados de topping de encurtidos.', 33000, TRUE, 15, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('entradas-guindadera', 'entradas', 'Guindadera', 'Trilogía de empanada de maíz con tinta de calamar pulpo, amarrilla con ropa vieja y blanca con camarones acompañada de suero y picante de la casa.', 27000, TRUE, 15, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('entradas-barichara', 'entradas', 'Barichara', 'Arepa de maíz viche con queso parmesano, crema de leche, leche de coco y…. láminas de queso costeño acompañado de chicharrón al horno y queso crema con topping de papaya biche.', 34000, TRUE, 15, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('entradas-mafufo', 'entradas', 'Mafufo', 'Croquetas apanadas, elaboradas con plátano de los montes de maría… con salsa de bisque cremoso y topping de camarones con eneldo.', 33000, TRUE, 15, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('entradas-tiradito-de-pescado-blanco', 'entradas', 'Tiradito de pescado blanco', 'Pesca blanca marinada con sal y limón; cortada en laminas finas sobre un espejo de leche de tigre cremoso con plumas de cebolla roja, aguacate, ají amarillo, cilantro y tajín.', 29000, TRUE, 15, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('entradas-ceviche-el-patio', 'entradas', 'Ceviche el patio', 'Camarones y langostinos marinados con limón y ají-no-moto; sobre un espejo de leche de coco con notas de jengibre y topping de mango y manzana verde acompañados de chips morados de plátano.', 36000, TRUE, 15, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('entradas-trilogia-campesina', 'entradas', 'Trilogía campesina', 'Trilogía de envueltos hechos por manos campesinas entre los cuales tenemos bollo de maíz fresco, bollo de yuca con anís y bollo maíz blanco con coco acompañados, chorizo artesanal, chicharon, suero artesanal, guiso criollo y queso costeño', 28000, TRUE, 15, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('entradas-carimanola', 'entradas', 'Carimañola', 'Croquetas de yuca rellenas de queso costeño, suero, lomo fino salteado y topping de cebolla y cilantro.', 28000, TRUE, 15, 'cocina', '[]'::jsonb);

-- Carnes
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('carnes-lomo-silvestre', 'carnes', 'Lomo silvestre', 'Lomo marinado con sal gruesa y polvo de ají de los montes de maría; bañado en salsa de vino tinto con notas de mostaza antigua y ajo rostizado. Acompañado de risotto con hongos silvestres y quesos parmesanos.', 67000, TRUE, 25, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('carnes-lomo-rustico-angus', 'carnes', 'Lomo rústico (angus)', 'Lomo de res marinado con sal gruesa, ajo rostizado y adobo ahumado; con pure de tomate seco, queso crema y chimichurri acompañado de polenta con queso.', 82000, TRUE, 25, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('carnes-cowboy', 'carnes', 'Cowboy', 'Lomo de res con hueso corto. Marinado con sal gruesa, paprika, vino tinto, pasta de ajo cubierto con pure rústico de espinaca y queso parmesano; acompañado de papas crocantes con sal de queso.', 96000, TRUE, 25, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('carnes-costilla-de-cerdo', 'carnes', 'Costilla de cerdo', 'Costilla de cerdo marinada con finas hierbas, salsa hoisin y ostras preparadas en cocción lenta por más de 3 horas; acompañado de pure de maíz fresco y albahaca gratinado.', 65000, TRUE, 25, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('carnes-solomito-de-cerdo', 'carnes', 'Solomito de cerdo', 'Solomito de cerdo al horno con glaseado de maracuyá, acompañado de pure de papa fino con notas de nuez moscada y salsa del día.', 57000, TRUE, 25, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('carnes-tomahawk-de-cerdo-700g', 'carnes', 'Tomahawk de cerdo 700g', 'Lomo ancho de cerdo con hueso marinado con sal gruesa, paprika, vino tinto, pasta de ajo cubierto con pure rústico de espinaca y queso parmesano; acompañante de su elección.', 71000, TRUE, 25, 'cocina', '[{"id":"mod_acompanante","nombre":"Acompañante","tipo":"seleccion_unica","obligatorio":true,"opciones":[{"nombre":"Papa francesa","precioAdicional":0},{"nombre":"Puré","precioAdicional":0},{"nombre":"Ensalada","precioAdicional":0},{"nombre":"Patacón","precioAdicional":0}]}]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('carnes-filet-mignon', 'carnes', 'Filet mignon', 'Lomo fino marinado con sal gruesa y pasta de ajo albordado con tocineta crocante y preparado al horno acompañado de pure de papa fino con notas de nuez moscada bañado con salsa de chocolate avellanado y notas de ron y ensalada del día.', 69000, TRUE, 25, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('carnes-entrecot-angus-400g', 'carnes', 'Entrecot (angus) 400g', 'Corte de res grueso marinado con sal parrilla y adobo ahumado; preparado al horno; acompañante de su elección.', 99000, TRUE, 25, 'cocina', '[{"id":"mod_acompanante","nombre":"Acompañante","tipo":"seleccion_unica","obligatorio":true,"opciones":[{"nombre":"Papa francesa","precioAdicional":0},{"nombre":"Puré","precioAdicional":0},{"nombre":"Ensalada","precioAdicional":0},{"nombre":"Patacón","precioAdicional":0}]}]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('carnes-punta-gorda-350g', 'carnes', 'Punta gorda 350g', 'Brocheta res marinada con sal parrilla y pasta de ajo rostizado, acompañado con papas confitadas con cebolla caramelizada y ensalada césar.', 55000, TRUE, 25, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('carnes-pave-de-res-gratinado-280g', 'carnes', 'Pave de res gratinado 280g', 'Lomo fino de res a la parrilla marinado con sal gruesa y ajo, fundido en queso con salsa fileto acompañado de polenta.', 69000, TRUE, 25, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('carnes-churrasco-5-quesos-madurado-300g', 'carnes', 'Churrasco 5 quesos madurado 300g', 'Corte de lomo ancho de res, marinado con sal gruesa y pasta de ajo, bañado en una salsa de 5 quesos y gratinado, con un acompañante a su elección.', 68000, TRUE, 25, 'cocina', '[{"id":"mod_acompanante","nombre":"Acompañante","tipo":"seleccion_unica","obligatorio":true,"opciones":[{"nombre":"Papa francesa","precioAdicional":0},{"nombre":"Puré","precioAdicional":0},{"nombre":"Ensalada","precioAdicional":0},{"nombre":"Patacón","precioAdicional":0}]}]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('carnes-t-bone-steak-angus-600g', 'carnes', 'T-bone steak angus 600g', 'Corte de res de muy alta calidad, marinado con sal gruesa y pasta de ajo, asado a la parrilla, y con un acompañante a su elección.', 130000, TRUE, 25, 'cocina', '[{"id":"mod_acompanante","nombre":"Acompañante","tipo":"seleccion_unica","obligatorio":true,"opciones":[{"nombre":"Papa francesa","precioAdicional":0},{"nombre":"Puré","precioAdicional":0},{"nombre":"Ensalada","precioAdicional":0},{"nombre":"Patacón","precioAdicional":0}]}]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('carnes-posta-negra', 'carnes', 'Posta negra', 'Morrillo de res, preparado en una cocción lenta por 72 horas en melao de panela y Coca-Cola, servido sobre un risotto de coco acompañado con plátano en reducción de Kola.', 55000, TRUE, 25, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('carnes-lomo-patio-280g', 'carnes', 'Lomo patio 280g', 'Lomo fino, marinado con mostaza antigua, sal gruesa y semillas de amapola, servido con un topping de vegetales acevichado y tocineta crocante, y con un acompañante a su elección.', 64000, TRUE, 25, 'cocina', '[{"id":"mod_acompanante","nombre":"Acompañante","tipo":"seleccion_unica","obligatorio":true,"opciones":[{"nombre":"Papa francesa","precioAdicional":0},{"nombre":"Puré","precioAdicional":0},{"nombre":"Ensalada","precioAdicional":0},{"nombre":"Patacón","precioAdicional":0}]}]'::jsonb);

-- Pescados y mariscos
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('pescados-y-mariscos-pescado-encocado', 'pescados-y-mariscos', 'Pescado encocado', 'Pescado marinado con cítricos, frito en tempura de ahuyama acompañado de risotto de titote, crema de leche y topping criollo peruano y polvo de hoja de yuca.', 57000, TRUE, 25, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('pescados-y-mariscos-langostinos-5-queso', 'pescados-y-mariscos', 'Langostinos 5 queso', 'Langostinos marinados con mostaza antigua, vino blanco, jengibre y sal; cocidos al horno con queso azul, tilsit ahumado, parmesano, camembert y brie acompañado de tostada de pan con hierbas y topping de frutos rojos silvestre.', 77000, TRUE, 25, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('pescados-y-mariscos-pez-leon-a-la-marinera', 'pescados-y-mariscos', 'Pez león a la marinera', 'NO RECOMENDADO PARA MUJERES EMBARAZADAS Y NIÑOS. Pez león deshuesado marinado con sal, ajo rostizado y hierbas frescas. Cocido al vacío bañado con salsa de marisco cremoso con polvo de hoja de yuca; acompañado de patacones crocante.', 74000, TRUE, 25, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('pescados-y-mariscos-caldereta', 'pescados-y-mariscos', 'Caldereta', 'Muelas de cangrejo, langosta, langostinos tigre, pescado del pacifico y anillos de calamar frito, bañados con reducción de bisque y brandy, acompañado patacones crocantes y aguacate.', 82000, TRUE, 25, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('pescados-y-mariscos-trilogia-de-mariscos', 'pescados-y-mariscos', 'Trilogía de mariscos', '- Langostinos con polenta. - Langosta con puré de papa trufado. - Muelas con arepa de yuca con queso.', 82000, TRUE, 25, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('pescados-y-mariscos-salmon-campesino', 'pescados-y-mariscos', 'Salmón Campesino', 'Filete de salmón, servido con queso campesino asado a la parrilla, acompañado con papa confitada con cebolla caramelizada y salsa de eneldo cítrica.', 68000, TRUE, 25, 'cocina', '[]'::jsonb);

-- Pastas artesanales
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('pastas-artesanales-pastas-jardinera', 'pastas-artesanales', 'Pastas jardinera', 'Pastas artesanales elaborada en casa. Cocidas con hierbas frescas y bañadas con salsa de albahaca y camarones acompañada de pan focaccia.', 46000, TRUE, 20, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('pastas-artesanales-lomo-enredado', 'pastas-artesanales', 'Lomo enredado', 'Pasta pappardelle artesanales elaboradas en casa; bañadas en salsa de mariscos blanca trufada y lomo fino marinado con finas hierbas y paprika con chimichurri ahumado y cebolla puerro.', 67000, TRUE, 20, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('pastas-artesanales-enredadera-de-marisco', 'pastas-artesanales', 'Enredadera de marisco', 'Pasta fetuccini artesanal elaborada en casa bañada en salsa de mariscos de vino blanco trufado con ajo rostizado y jengibre acompañado con focaccia de hierbas', 58000, TRUE, 20, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('pastas-artesanales-pastas-fileto', 'pastas-artesanales', 'Pastas fileto', 'Pastas artesanales bañadas con salsa fileto con albahaca, milanesa de pollo y queso frito acompañado de pan focaccia de hierbas', 47000, TRUE, 20, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('pastas-artesanales-pastas-veloute-de-mariscos', 'pastas-artesanales', 'Pastas veloute de mariscos', 'Pasta artesanal elaborada en casa bañada con bisques y leche de coco, mariscos frescos marinados con pasta de ajo, jengibre y vino blanco acompañado con focaccia de hierbas.', 58000, TRUE, 20, 'cocina', '[]'::jsonb);

-- Aves
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('aves-pollo-relleno', 'aves', 'Pollo relleno', 'Pechuga rellena de espinaca, queso crema, queso mozzarella y almendra acompañado de pure de ñame de los montes de maría, pure de berenjena del huerto y salsa criolla de la abuela bañada en salsa pesto rojo.', 52000, TRUE, 20, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('aves-pierna-pernil', 'aves', 'Pierna pernil', 'Pierna pernil de pollo deshuesado, marinado con sal gruesa, paprika y finas hierbas acompañada de papas criollas al limón en salsa de chimichurri de ahumada.', 47000, TRUE, 20, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('aves-suprema-al-horno', 'aves', 'Suprema al horno', 'Pechuga en corte mariposa marinada con pasta de ajo, finas hierbas preparada al horno acompañada de papa francesa con sal de queso', 45000, TRUE, 20, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('aves-medalla-de-pollo', 'aves', 'Medalla de pollo', 'Medallones de pollo marinados con sal y ajo rostizado con salsa fileto y topping de queso frito acompañado de papa crocante con sal de queso', 54000, TRUE, 20, 'cocina', '[]'::jsonb);

-- Arroces
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('arroces-arroz-caldoso-con-lomo', 'arroces', 'Arroz caldoso con lomo', 'Arroz preparado con pasta de ají amarrilo peruano, mariscos marinados con salsa soya, jengibre; salteado con maíz, arvejas, pimentones y cilantro acompañado de lomo fino frito.', 66000, TRUE, 25, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('arroces-arroz-costeno', 'arroces', 'Arroz costeño', 'Arroz titote salteado con aceite sésamo, pollo, lomo de res, camarones, chicharrón y queso frito costeño.', 59000, TRUE, 25, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('arroces-risotto-de-hongo', 'arroces', 'Risotto de hongo', 'Arroz risotto preparado con reducción de vino blanco salteado con hongos silvestre y velouté de champiñones a, queso costeño deshidratado, tocineta crocante y polvo de hoja de yuca.', 47000, TRUE, 25, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('arroces-risotto-marinera', 'arroces', 'Risotto marinera', 'Arroz risotto, con mix de mariscos marinados con pasta de ajo, salteados al wok con vino blanco, bisque, leche de coco y salsa fileto con polvo de queso costeño y limón.', 58000, TRUE, 25, 'cocina', '[]'::jsonb);

-- Picada
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('picada-picada-mar-y-tierra-para-4-pax', 'picada', 'Picada mar y tierra para 4 pax', 'Camarones apanados, chicharrón de filete de tilapia calamares apanados marinados con mostaza antigua, vino blanco, pasta de ajo y zumo de jengibre, brochetas de pollo lomo fino y lomo de cerdo, marinados con pasta de ajo y adobo ahumado; costilla san Luis junior preparada en cocción lenta con salsa pasión, filete de pechuga, chorizo artesanal, acompañado de queso frito, trilogía de bollos, arepa de maíz biche, papa casco artesanal, empanadas, palitos de yuca con salsa de pepinillo, patacones', 220000, TRUE, 35, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('picada-picada-al-horno', 'picada', 'Picada al horno', 'Chuleton de cerdo, chorizo artesanal, bombon de pollo con bbq, acompañada de arepa de yuca rellena.', 78000, TRUE, 35, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('picada-mix-de-brochetas', 'picada', 'Mix de brochetas', 'Brocheta de lomo de res, filete de pechuga, lomo de cerdo y vegetales asado a la parrilla, acompañada de variedad de bollos, butifatta de la casa y salsa de ajo rostizado.', 60000, TRUE, 35, 'cocina', '[]'::jsonb);

-- Express
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('express-hamburguesa-de-res-y-espinaca', 'express', 'Hamburguesa de res y espinaca', 'Carne de res a la parrilla fundida con queso emmental, cebolla con panela, pure de espinaca, tomate verde en rodaja, salsa de pepinillo y pan artesanal de orégano acompañada de papas a la francesa crocante', 36000, TRUE, 15, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('express-hamburguesa-de-res-y-cebolla-caramelizada', 'express', 'Hamburguesa de res y cebolla caramelizada', 'Carne de res a la parrilla bañada de queso doble crema, cebolla caramelizada con corozo salsa de pepinillo con pan artesanal de la casa y salsa de pepinillo', 34000, TRUE, 15, 'cocina', '[]'::jsonb);

-- Infantil
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('infantil-dedos-de-pollo-rellenos-con-queso', 'infantil', 'Dedos de pollo rellenos con queso', 'Dedos de pollo rellenos de queso mozzarella acompañado de francesa crocante, salsa de tomate y pepinillos.', 25000, TRUE, 15, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('infantil-baby-beef-junior-180g', 'infantil', 'Baby beef junior 180g', 'Lomo fino a la plancha acompañado de papa crocante.', 30000, TRUE, 15, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('infantil-queso-mozzarella-apanados', 'infantil', 'Queso mozzarella apanados', 'Dedos de queso mozzarella apanados, acompañados de papas a la francesa crocante y salsa de la casa.', 26000, TRUE, 15, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('infantil-pechuguita-junior-180g', 'infantil', 'Pechuguita Junior 180g', 'Filete de pechuga a la plancha acompañado de papas a la francesa', 27000, TRUE, 15, 'cocina', '[]'::jsonb);

-- Postre
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('postre-volcan-de-chocolate', 'postre', 'Volcán de chocolate', 'Postre horneado relleno con chocolate, acompañado con helado y salsa de frutos rojos y notas de ron.', 29000, TRUE, 10, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('postre-dulce-recuerdo', 'postre', 'Dulce recuerdo', 'Inspirado en la niñez, es un postre con arroz con leche, crema de leche, leche condensada, leche en polvo, bañado con frutos amarillos, merengue suizo flameado a la mesa.', 27000, TRUE, 10, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('postre-banana-caliente', 'postre', 'Banana caliente', 'Banano asado a la parrilla, bañado con salsa de Kola y leche, acompañado de helado de vainilla.', 25000, TRUE, 10, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('postre-brownie-de-red-velvet', 'postre', 'Brownie de red velvet', '100% chocolate horneado con cheesecake y servido con helado de vainilla.', 28000, TRUE, 10, 'cocina', '[]'::jsonb);
INSERT INTO items_carta (id, categoria_id, nombre, descripcion, precio, disponible, tiempo_preparacion_min, destino, modificadores) VALUES ('postre-tartaleta-el-patio', 'postre', 'Tartaleta el patio', 'Tartaleta rellena con mousse de chocolate blanco y coco, acompañado de frutos amarillos y coco caramelizado.', 30000, TRUE, 10, 'cocina', '[]'::jsonb);
